name: Build CV PDF

on:
  push:
    branches:
      - main
    paths:
      - PDF/**
      - .github/workflows/build-cv.yml

jobs:
  build:
    name: Compilar LaTeX
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: xu-cheng/texlive-action@v3
        with:
          scheme: small
          texlive_version: latest
          run: |
            echo -e "-----------\n"

            echo -e "> tlmgr update --self\n"
            tlmgr update --self

            echo -e "> tlmgr install \n"
            tlmgr install newcomputermodern fontsetup titlesec

            cd PDF

            echo "🦀> latexmk pt.tex"
            latexmk -xelatex main.tex

            echo "🦀> latexmk en.tex"
            latexmk -xelatex en.tex

            echo "🦀> cp PDF/main.pdf Heliton-CV-pt.pdf && cp PDF/en.pdf Heliton-CV-en.pdf"
            cp main.pdf ../Heliton-CV-pt.pdf
            cp en.pdf ../Heliton-CV-en.pdf

      - name: Publicar release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          DATE_STR="$(date -u +'%Y-%m-%d')"
          TAG_NAME="${DATE_STR}-${GITHUB_SHA::7}"

          echo -e "@hellmrf's _Curriculum Vitae_ (PDF version) was updated! \n\n- 🇧🇷  Português: [\`${TAG_NAME}\`](https://github.com/hellmrf/hellmrf/releases/download/${TAG_NAME}/Heliton-CV-pt.pdf) | [\`latest\`](https://github.com/hellmrf/hellmrf/releases/latest/download/Heliton-CV-pt.pdf) \n- 🇬🇧  English: [\`${TAG_NAME}\`](https://github.com/hellmrf/hellmrf/releases/download/${TAG_NAME}/Heliton-CV-en.pdf) | [\`latest\`](https://github.com/hellmrf/hellmrf/releases/latest/download/Heliton-CV-en.pdf) \n\n_Build automático do commit ${GITHUB_SHA}._" > RELEASE.md

          gh release create "${TAG_NAME}" \
            --title "${DATE_STR} | @hellmrf's CV.pdf" \
            --notes-file RELEASE.md \
            --target "${GITHUB_SHA}" \
            --draft \
            Heliton-CV-pt.pdf \
            Heliton-CV-en.pdf
