name: Build CV PDF

on:
  push:
    branches:
      - main
    paths:
      - PDF/**
  workflow_dispatch:

jobs:
  build:
    name: Compilar LaTeX
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: xu-cheng/texlive-action@v3
        with:
          scheme: small
          texlive_version: latest
          run: |
            echo -e "-----------\n"

            echo -e "> tlmgr install arara\n"
            tlmgr install arara

            echo -e "> which arara\n"
            which arara

            echo -e "\n\n> arara -d PDF -v main.tex\n"
            arara -d PDF -v main.tex

            echo -e "\n\n> arara -d PDF -v en.tex\n"
            arara -d PDF -v en.tex

            echo -e "\n\n> cp PDF/main.pdf Heliton-CV-pt.pdf && cp PDF/en.pdf Heliton-CV-en.pdf"
            cp PDF/main.pdf Heliton-CV-pt.pdf
            cp PDF/en.pdf Heliton-CV-en.pdf

      - name: Publicar release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          DATE_STR="$(date -u +'%Y-%m-%d')"
          TAG_NAME="${DATE_STR}-${GITHUB_SHA::7}"

          gh release create "${TAG_NAME}" \
            --title "@hellmrf's CV.pdf | ${DATE_STR}" \
            --notes "@hellmrf's _Curriculum Vitae_ (PDF version) was updated!\n\n- Português: [`${TAG_NAME}`](https://github.com/hellmrf/hellmrf/releases/download/${TAG_NAME}/Heliton-CV-pt.pdf) | [`latest`](https://github.com/hellmrf/hellmrf/releases/latest/download/Heliton-CV-pt.pdf)\n- English: [`${TAG_NAME}`](https://github.com/hellmrf/hellmrf/releases/download/${TAG_NAME}/Heliton-CV-en.pdf) | [`latest`](https://github.com/hellmrf/hellmrf/releases/latest/download/Heliton-CV-en.pdf)\n\n_Build automático do commit ${GITHUB_SHA}._" \
            --target "${GITHUB_SHA}" \
            --latest \
            Heliton-CV-pt.pdf \
            Heliton-CV-en.pdf
